<?php
// Start: Building System
include("mode_setting.php");
$fun = $_GET['fun'];

if($fun == 'get_sheet') {
	
	$data=$obj_salesreport->get_sheet($_POST['f_date'],$_POST['t_date'],$_POST['m_value'],$_POST['full_inv'],$_POST['user_name']);	
	//printr($_POST);
	      $explode=explode("=",$_POST['user_name']);
		    $user_id = $explode[1];
    		$user_type_id = $explode[0];
	$html = '';
		if(!empty($data))
		{
			 	$html .= '<div class="table-responsive">';
					 $html .= '<table class="tool-row b-t text-small" id="myTable" border="1">';
					 $html .= ' <thead>';
			             
			             if($_POST['n']==1)
			                $html .= ' <tr><td colspan="10"><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="get_report()"><i class="fa fa-print"></i> Excel</a></span></td></tr>';
			            $html .= ' <tr>'; 
    						if($_POST['full_inv']=='1')
    						{
    						    $html .= ' 
    						               <th>Sr. No</th>
    						               <th>Invoice No</th>
    						               <th>Customer Name</th>
    						               <th>Email</th>
    						               <th>Invoice Date</th>
    						               <th>Receivable Amount</th>
    						               <th>Total VAT</th>
    						               <th>Active  / Inactive / Cancel</th>
    						               <th>Saved / Not Saved</th>
    						               <th>Deleted</th>
    						               <th>Generated By</th>
    						               <th>Invoice Generated Date</th>';
    						}
    						else
    						{
        						 
        						 	 
        						 	 $html .= ' <th  colspan="7"></th>';
        							 $html .= ' <th colspan="2">Previous Month</th>';	
        							 $html .= ' <th colspan="2">Corresponding Month</th>';	
        						 $html .= ' </tr>';
        						 $html .= ' <tr>
        						                <th>Sr. No</th>';
        						 	 $html .= ' <th>Product Code</th>';
        							 $html .= ' <th>Product Decription</th>';
        							 $html .= ' <th>Qty</th>';
        							 $html .= ' <th>Rack Qty</th>';
        							 $html .= ' <th>Other Charges GST</th>';	
        							 $html .= ' <th>Total Amount</th>';
        							 $html .= ' <th>Qty</th>';
        							 $html .= ' <th>Total Amount</th>';
        							 $html .= ' <th>Qty</th>';
        							 $html .= ' <th>Total Amount</th>';
        						 
    		                }
		                $html .= ' </tr>';
					 $html .= ' </thead>';
					  $html .= '<tbody>';
					  $i=$qty=$tot_amt=$pre_qty=$pre_amt=$corr_qty=$corr_amt=$rack_total_qty=0;$k=1;
						 foreach($data as $v)
								{
								    
								   // printr($v);
								     if($user_type_id==0){
								         $user_type_id=$_SESSION['LOGIN_USER_TYPE'];
								         $user_id=$_SESSION['ADMIN_LOGIN_SWISS'];
								     }
								      
								    	$rack_qty = $obj_rack_master->getRackQty($v['product_code_id'],$user_type_id,$user_id,'','');
        						    	 $rm_qty=0;$total_rm_qty=0;
        						    	 
								    $style ="style='background-color: aliceblue;'";
                                    if($i%2==0)
                                        $style ="style='background-color: antiquewhite;'";
                                        
									  $html .= '<tr '.$style.'>';
									  if($_POST['full_inv']=='1')
    						          {   
    						              $act = '<b style="color:red;">Inactived</b>';
    						              if($v['status']=='1')
    						                $act = 'Active';
    						              if($v['status']=='2')
    						                $act = '<b style="color:red;">Cancel</b>';
    						                
    						              $del = $save = '';
    						              if($v['is_delete']==1)
    						                $del ='<b style="color:red;">Deleted</b>';
    						                
    						              if($v['gen_status']==1)
    						                $save ='<b style="color:red;">Not Saved</b>';
    						              $user_name = $obj_salesreport->getUser($v['user_id'],$v['user_type_id']);
    						              $html .= '<th> '.$k.'</th>
    						                        <th> '.$v['invoice_no'].'</th>
    						                        <td> '.$v['customer_name'].'</td>
    						                        <td> '.$v['email'].'</td>
    						                        <td> '.dateFormat(4,$v['invoice_date']).'</td>
    						                        <td> ';
        						                        if($user_name['country_id']=='155'){
        						                            $html.=$v['amt_maxico'];$amt=$v['amt_maxico'];}
        						                        else{
        						                            $html.=$v['amount_paid'];$amt=$v['amount_paid'];
        						                            
        						                        }
        						                           
        						                  $amount =((($amt-$v['delivery_charges'])*100)/(100+$v['tax_maxico']));
        						                  $vat = ($amount* $v['tax_maxico'])/100;
    						              $html .= '</td>
    						                        <td>'.number_format($vat,2).' </td>
    						                        <td> '.$act.'</td>
    						                        <td> '.$save.'</td>
    						                        <td> '.$del.'</td>
    						                        <th> '.$user_name['name'].'</th>
    						                        <th> '.dateFormat(4,$v['date_added']).'</th>';
    						              $tot_vat +=$vat;
    						              $tot_amt +=$v['final_total'];
    						              $pre_amt +=$amt;
    						          }
    						          else
    						          {
    									 if($user_name['country_id']=='155'){
				                            $amt=$v['amt_maxico'];}
				                        else{
        						            $amt=$v['amount_paid'];}
    									 $amount =((($amt-$v['delivery_charges'])*100)/(100+$v['tax_maxico']));
        						                  $vat = ($amount* $v['tax_maxico'])/100;
    									  $html .= '<th> '.$k.'</th>
    									            <td> '.$v['product_code'].'</td>';
    									  $html .= '<td> '.$v['description'].'</td>';
    									  $html .= '<td> '.$v['total_qty'].'</td>';
                            						if(!empty($rack_qty))
                            						{ 
                            							foreach($rack_qty as $rack)
                            							{
                                					        	$dispatch_qty=$obj_rack_master->gettotaldispatchSales($rack['stock_id'],$user_type_id,$user_id);
                                								$rm_qty=$rack['store_qty']-$dispatch_qty['total'];
                                							    $total_rm_qty=$total_rm_qty+$rm_qty;    
                                						}
                            						}
                            				
                            		      $html .= '<td>'.$total_rm_qty.'</td>';
    									  $html .= '<td> '.$v['gst'].'</td>';
    									  $html .= '<td> '.$v['total_amount'].'</td>';
    									  $html .= '<td> '.$v['previous_qty'].'</td>';
    									  $html .= '<td> '.$v['previous_amount'].'</td>';
    									  $html .= '<td> '.$v['corresponding_qty'].'</td>';
    									  $html .= '<td> '.$v['corresponding_amount'].'</td>';
    									  $qty +=$v['total_qty'];
    									  $rack_total_qty +=$total_rm_qty;
    									  $tot_amt +=$v['total_amount'];
    									  $tot_vat +=$vat;
    									  $pre_qty +=$v['previous_qty'];
    									  $pre_amt +=$v['previous_amount'];
    									  $corr_qty +=$v['corresponding_qty'];
    									  $corr_amt +=$v['corresponding_amount'];
    						          }
									  $html .= '</tr>';//die;
									  $i++;$k++;
								}
								$html.='<tr>';
    								if($_POST['full_inv']!='1'){
    								    $html.='<td colspan="3"><b>Total</b></td>
    								            <td>'.$qty.'</td>
    								            <td>'.$rack_total_qty.'</td>
    								            <td></td>
    								            <td>'.$tot_amt.'</td>
    								            <td>'.$pre_qty.'</td>
    								            <td>'.$pre_amt.'</td>
    								            <td>'.$corr_qty.'</td>
    								            <td>'.$corr_amt.'</td>';
    								}
    								else
    								{//<td>'.$tot_amt.'</td>
    								    $html.='<td colspan="5"><b>Total</b></td>
    								            <td>'.$pre_amt.'</td>
    								            <td>'.$tot_vat.'</td>
    								            <td colspan="5"></td>';
    								}
								$html.='</tr>';
					$html .= ' </tbody>';
			    $html .= ' </table>';
			$html .= ' </div>';
	 	
	}
	
	else
	{
		echo "<center><b> There are no record available</b></center>";		
	}
	  
	echo $html;
		
	
}
if($fun == 'getreport') {
    //printr($_POST);die;
    $data=$obj_salesreport->get_report($_POST['f_date'],$_POST['t_date'],$_POST['check']);
   printr($data);
    $prev_month = date('Y-m-d', strtotime($_POST['f_date'].' -1 month'));
    $corre_month = date('Y-m-d', strtotime($_POST['f_date'].' -12 month'));
    $html = '';
		if(!empty($data))
		{
		    $html .= '<div class="table-responsive">
    		                    <table class="tool-row table-striped  b-t text-small" border="1">
    		                        <tbody>';
                            		    if($_POST['check']=='1')
                                        {
                                                   if($_POST['num']==1)
			                                            $html .= ' <tr><td colspan="18"><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports()"><i class="fa fa-print"></i> Excel</a></span></td></tr>';
                                		           $html .= '  <tr >
                    					                            <th rowspan="3" style="background-color: beige;"><center>State</center></th>
                    					                            <th colspan="5" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $_POST['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $_POST['f_date'])->format("Y").'</center></th>
                    					                            <th colspan="5" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $prev_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $prev_month)->format("Y").'</center></th>
                    					                            <th colspan="5" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $corre_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d",$corre_month)->format("Y").'</center></th>
                						                       </tr>
                						                       <tr >';
                						                            for($i=1;$i<=3;$i++)
                						                            {
                        					                            $html .= '<th colspan="2"><center>New Customers</center></th>
                                					                            <th colspan="2"><center>Repeated Customers</center></th>
                                					                            <th rowspan="2" style="width: 30%;"><center>New VS Repeated</center></th>';
                						                            }
                						               $html .= '</tr>
                						                       <tr>';
                    					                            for($i=1;$i<=6;$i++)
                						                            {
                        					                             $html .= '<th style="background-color: lightblue;">Total Amount</th>
                                    					                          <th style="background-color: lightblue;">No. Of Customers</th>';
                						                            }
                    					                            
                    					                $html .= '</tr>'; 
                    					                $t_cust = $t_cust_pre = $t_cust_corr = $pre_prs=$corr_prs=$curr_prs=0;
                    		                            foreach($data as $key=>$d)
                    						            {
                    						                  if($key=='email')
                    						                  {
                    						                      
                    						                      foreach($d as $state=>$v)
                            						              {
                        						                      $prev_email =$corr_email=array(); 
                        						                      $curr_email = explode(',',$v['email']);
                        						                      if($v['previous_email']!='')
                        						                        $prev_email = explode(',',$v['previous_email']);
                        						                      if($v['corresponding_email']!='')
                        						                        $corr_email = explode(',',$v['corresponding_email']);
                        						                      
                        						                      $corr_prev = array_intersect($corr_email,$prev_email);
                        						                      
                        						                      $curr_output = array_unique(array_merge($prev_email, $corr_email));
                        						                      $current_email =array_intersect($curr_output,$curr_email);
                        						                      
                        						                      $result_curr=array_diff($curr_email,$current_email);
                        						                      $result_prev=array_diff($prev_email,$corr_prev);
                        						                      
                        						                      $total_prev_rep = $obj_salesreport->gettotalamount(implode ( "', '", $corr_prev ),$prev_month,$data[$state]['abbreviation']);
                        						                      $total_curr_rep = $obj_salesreport->gettotalamount(implode ( "', '", $current_email ),$_POST['f_date'],$data[$state]['abbreviation']);
                        						                      
                        						                      
                        						                      $html .= '<tr>
                                    					                            <th style="background-color: bisque;">'.$state.'</th>
                                    					                            <td style="text-align: right;">'.number_format(($data[$state]['total_amt']-$total_curr_rep['total_amt']),2).'</td>
                                    					                            <td style="text-align: right;" id="get_email" data-currentval="'.(implode(",",$curr_email)).'">
                                    					                           
                                    					                           <a data-trigger="hover"  data-toggle="popover" data-html="true" data-placement="top" data-poload="" title="<pre>'.implode(",\n",$result_curr).'</pre>"><div>'.($data[$state]['total_cust']-count($current_email)).'</div></a>
                                    					                            
                                    					                            </td>
                                    					                            <td style="text-align: right;">'.number_format($total_curr_rep['total_amt'],2).'</td>
                                    					                            <td style="text-align: right;"><a data-trigger="hover"  data-toggle="popover" data-html="true" data-placement="top" data-poload="" title="<pre>'.implode(",\n",$current_email).'</pre>"><div>'.count($current_email).'</div></a></td>
                                    					                            <td><b style="color:red">Repeated : </b>'.number_format((($total_curr_rep['total_amt']*100)/$data[$state]['total_amt']),2).'%<br>
                                    					                                <b style="color:green">New : </b>'.number_format(((($data[$state]['total_amt']-$total_curr_rep['total_amt'])*100)/$data[$state]['total_amt']),2).'%
                                    					                            </td>
                                    					                            <td style="text-align: right;">'.number_format(($data[$state]['previous_amount']-$total_prev_rep['total_amt']),2).'</td>
                                    					                            <td style="text-align: right;"><a data-trigger="hover"  data-toggle="popover" data-html="true" data-placement="top" data-poload="" title="<pre>'.implode(",\n",$result_prev).'</pre>"><div>'.(count($prev_email)-count($corr_prev)).'</div></a></td>
                                    					                            <td style="text-align: right;">'.number_format($total_prev_rep['total_amt'],2).'</td>
                                    					                            <td style="text-align: right;"><a data-trigger="hover"  data-toggle="popover" data-html="true" data-placement="top" data-poload="" title="<pre>'.implode(",\n",$corr_prev).'</pre>"><div>'.count($corr_prev).'</div></a></td>
                                    					                            <td><b style="color:red">Repeated : </b>'.number_format((($total_prev_rep['total_amt']*100)/$data[$state]['previous_amount']),2).'%<br>
                                    					                                <b style="color:green">New : </b>'.number_format(((($data[$state]['previous_amount']-$total_prev_rep['total_amt'])*100)/$data[$state]['previous_amount']),2).'%
                                    					                            </td>
                                    					                            <td style="text-align: right;">'.number_format($data[$state]['corresponding_amount'],2).'</td>
                                    					                            <td style="text-align: right;"><a data-trigger="hover"  data-toggle="popover" data-html="true" data-placement="top" data-poload="" title="<pre>'.implode(",\n",$corr_email).'</pre>"><div>'.count($corr_email).'</div></a></td>
                                    					                            <td style="text-align: right;">0</td>
                                    					                            <td style="text-align: right;">0</td>
                                    					                            <td><b style="color:red">Repeated : </b>'.number_format(((0*100)/$data[$state]['corresponding_amount']),2).'%<br>
                                    					                                <b style="color:green">New : </b>'.number_format(((($data[$state]['corresponding_amount']-0)*100)/$data[$state]['corresponding_amount']),2).'%
                                    					                            </td>
                                						                       </tr>';
                                						                       
                                						                $matrix[$state] = array('total_amt' => $data[$state]['total_amt'],
                                						                                        'total_amt_rep' => $total_curr_rep['total_amt'],
                                						                                        'previous_amount' => $data[$state]['previous_amount'],
                                						                                        'previous_amount_rep' => $total_prev_rep['total_amt'],
                                						                                        'corresponding_amount' => $data[$state]['corresponding_amount'],
                                						                                        'corresponding_amount_rep' => '0',);
                            						              }
                    						                  }
                                            
                    						            }
                    					                
                                        }
                                        else if($_POST['check']=='0')
                                        {           
                                                            if($_POST['num']==1)
			                                                    $html .= ' <tr><td colspan="11"><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports()"><i class="fa fa-print"></i> Excel</a>&nbsp;&nbsp;&nbsp;<a class="label bg-info pdfcls" href="javascript:void(0);" onclick="getreportpdf()"><i class="fa fa-print"></i> PDF</a></span></td></tr>';
                                		           
                                                               $html .= '<tr >
                    					                            <th rowspan="2" style="background-color: beige;"><center>State</center></th>
                    					                            <th colspan="3" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $_POST['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $_POST['f_date'])->format("Y").'</center></th>
                    					                            <th colspan="3" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $prev_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $prev_month)->format("Y").'</center></th>
                    					                            <th colspan="3" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $corre_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d",$corre_month)->format("Y").'</center></th>
                						                       </tr>
                						                       <tr>
                    					                            <th style="background-color: lightblue;">Total Amount</th>
                    					                            <th style="background-color: lightblue;">Total Customers</th>
                    					                            <th style="background-color: lightblue;">% to total sales</th>
                    					                            <th style="background-color: lightblue;">Total Amount</th>
                    					                            <th style="background-color: lightblue;">Total Customers</th>
                    					                            <th style="background-color: lightblue;">% to total sales</th>
                    					                            <th style="background-color: lightblue;">Total Amount</th>
                    					                            <th style="background-color: lightblue;">Total Customers</th>
                    					                            <th style="background-color: lightblue;">% to total sales</th>
                    					                       </tr>';
                						                       
                						                       $t_cust = $t_cust_pre = $t_cust_corr = $pre_prs=$corr_prs=$curr_prs=0;
                            		                            foreach($data as $key=>$d)
                            						            {
                                						               if($key != 'Total' && $key!='email' && $key!='Total_pre' && $key!='Total_cor' && $key!='abbreviation')
                                                                	   {
                                    						               $pre = number_format(($d['previous_amount']*100)/$data['Total_pre'],2);
                                    						               if($pre == 'nan')
                                    						                    $pre = 0;
                                    						               $corr = number_format(($d['corresponding_amount']*100)/$data['Total_cor'],2);
                                    						               if($corr == 'nan')
                                    						                    $corr = 0;
                                    						               $html .= '<tr>
                                        					                            <th style="background-color: bisque;">'.$key.'</th>
                                        					                            <td style="text-align: right;">'.$d['total_amt'].'</td>
                                        					                            <td style="text-align: right;">'.$d['total_cust'].'</td>
                                        					                            <td style="text-align: right;"> '.number_format((($d['total_amt']*100)/$data['Total']),2).' % </td>
                                        					                            <td style="text-align: right;">'.$d['previous_amount'].'</td>
                                        					                            <td style="text-align: right;">'.$d['previous_cust'].'</td>
                                        					                            <td style="text-align: right;"> '.$pre.' % </td>
                                        					                            <td style="text-align: right;">'.$d['corresponding_amount'].'</td>
                                        					                            <td style="text-align: right;">'.$d['corresponding_cust'].'</td>
                                        					                            <td style="text-align: right;"> '.$corr.' % </td>
                                    						                       </tr>';
                                    						                $t_cust += $d['total_cust'];
                                    						                $t_cust_pre += $d['previous_cust'];
                                    						                $t_cust_corr += $d['corresponding_cust'];
                                    						                $dataPoints [] = array("label"=>$key, "y"=>number_format((($d['total_amt']*100)/$data['Total']),2));
                                    						                $dataPoints_corr [] = array("label"=>$key, "y"=>$corr);
                                    						                $dataPoints_pre [] = array("label"=>$key, "y"=>$pre);
                                    						                $pre_prs +=$pre;
                                    						                $corr_prs +=$corr;
                                    						                $curr_prs +=number_format((($d['total_amt']*100)/$data['Total']),2);
                                                                	   }
                                                                	   else if($key == 'Total')
                                                                	   {
                                                                	       $html .= '<tr>
                                        					                            <th style="background-color: bisque;">'.$key.'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$data['Total'].'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$t_cust.'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;"> '.$curr_prs.' % </th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$data['Total_pre'].'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$t_cust_pre.'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;"> '.$pre_prs.' % </th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$data['Total_cor'].'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;">'.$t_cust_corr.'</th>
                                        					                            <th style="background-color: lightblue;text-align: right;"> '.$corr_prs.' % </th>
                                    						                       </tr>';
                                                                	   }
                            						                
                            						            }
                                		              
                                        }
                                        else if($_POST['check']=='2')
                                        {
                                            if($_POST['num']==1)
			                                  $html .= ' <tr><td colspan="13"><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports()"><i class="fa fa-print"></i> Excel</a></span></td></tr>';
                                		    
                                		    $html .= '<tr>
        					                            <th rowspan="2" style="background-color: beige;"><center>State</center></th>
        					                            <th colspan="4" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $_POST['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $_POST['f_date'])->format("Y").'</center></th>
        					                            <th colspan="4" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $prev_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $prev_month)->format("Y").'</center></th>
        					                            <th colspan="4" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $corre_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d",$corre_month)->format("Y").'</center></th>
    						                         </tr>
    						                         <tr>';
        					                                for($i=1;$i<=3;$i++)
        						                            {
                					                             $html .= '<th>Coffee Industry</th>
                            					                           <th>Tea Industry</th>
                            					                           <th>Food</th>
                            					                           <th>Other Industries (Non Food)</th>';
        						                            }
        					                 $html .='</tr>';
        					                 foreach($data as $key=>$d)
                            				 {
                            				     $html .= '<tr>
                					                            <th style="background-color: beige;">'.$key.'</th>
                					                            <td>'.number_format($d['current']['Coffee Industry'],2).'</td>
                					                            <td>'.number_format($d['current']['Tea Industry'],2).'</td>
                					                            <td>'.number_format($d['current']['Food'],2).'</td>
                					                            <td>'.number_format($d['current']['Other Industries (Non Food)'],2).'</td>
                					                            <td>'.number_format($d['previous']['Coffee Industry'],2).'</td>
                					                            <td>'.number_format($d['previous']['Tea Industry'],2).'</td>
                					                            <td>'.number_format($d['previous']['Food'],2).'</td>
                					                            <td>'.number_format($d['previous']['Other Industries (Non Food)'],2).'</td>
                					                            <td>'.number_format($d['corresponding']['Coffee Industry'],2).'</td>
                					                            <td>'.number_format($d['corresponding']['Tea Industry'],2).'</td>
                					                            <td>'.number_format($d['corresponding']['Food'],2).'</td>
                					                            <td>'.number_format($d['corresponding']['Other Industries (Non Food)'],2).'</td>
            						                       </tr>';
                            				 }
                                        }
                $html .= '</tbody>
                        </table>
                    </div>';
		}
	    if($_POST['check']=='1')
        {
            $html.='<div class="form-group"> </div>
                    <div class="table-responsive"> 
                        <table class="tool-row table-striped  b-t text-small" border="1">
                            <thead>
                                <tr>
                                    <th rowspan="2" colspan="2" style="background-color: beige;"><center>State</center></th>
    					            <th colspan="2" style="background-color: beige;"><h4><center>'.DateTime::createFromFormat('Y-m-d', $_POST['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $_POST['f_date'])->format("Y").'</center></h4></th>
    					            <th colspan="2" style="background-color: beige;"><h4><center>'.DateTime::createFromFormat('Y-m-d', $prev_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $prev_month)->format("Y").'</center></h4></th>
    					            <th colspan="2" style="background-color: beige;"><h4><center>'.DateTime::createFromFormat('Y-m-d', $corre_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d",$corre_month)->format("Y").'</center></h4></th>
                                    <th rowspan="2" style="background-color: beige;"><center>Total</center></th>
                                </tr>
                                <tr>';
		                            for($i=1;$i<=3;$i++)
		                            {
			                            $html .= '<th style="background-color: lightblue;"><center>New Customers</center></th>
					                              <th style="background-color: lightblue;"><center>Repeated Customers</center></th>';
		                            }
                    $html.='    </tr>
                            </thead>
                            <tbody>';
                                    $t_corr_rep = $t_corr = $t_prev_rep = $t_prev= $t_curr_rep = $t_curr =0;
                                    foreach($matrix as $key=>$v)
                                    {
                                        $html.='<tr>
                                                    <th colspan="2" style="background-color:bisque;">'.$key.'</th>
                                                    <td style="text-align: right;">'.number_format($v['total_amt']-$v['total_amt_rep'],2).'</td>
                                                    <td style="text-align: right;">'.number_format($v['total_amt_rep'],2).'</td>
                                                    <td style="text-align: right;">'.number_format($v['previous_amount']-$v['previous_amount_rep'],2).'</td>
                                                    <td style="text-align: right;">'.number_format($v['previous_amount_rep'],2).'</td>
                                                    <td style="text-align: right;">'.number_format($v['corresponding_amount']-$v['corresponding_amount_rep'],2).'</td>
                                                    <td style="text-align: right;">'.number_format($v['corresponding_amount_rep'],2).'</td>';
                                                    $t_curr += $v['total_amt']-$v['total_amt_rep'];
                                                    $t_curr_rep += $v['total_amt_rep'];
                                                    $t_prev += $v['previous_amount']-$v['previous_amount_rep'];
                                                    $t_prev_rep += $v['previous_amount_rep'];
                                                    $t_corr += $v['corresponding_amount']-$v['corresponding_amount_rep'];
                                                    $t_corr_rep += $v['corresponding_amount_rep'];
                                                    $row_total = ($v['total_amt']-$v['total_amt_rep'])+$v['total_amt_rep']+($v['previous_amount']-$v['previous_amount_rep'])+$v['previous_amount_rep']+$v['corresponding_amount']-$v['corresponding_amount_rep']+$v['corresponding_amount_rep'];
                                                    $html.='<th style="background-color:lightblue;text-align: right;">'.$row_total.'</th>';
                                         $html.='</tr>';
                                    }
                                    $html.='<tr>
                                             <th colspan="2" style="background-color: beige;"> Total </th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_curr,2).'</th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_curr_rep,2).'</th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_prev,2).'</th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_prev_rep,2).'</th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_corr,2).'</th>
                                             <th style="background-color:lightblue;text-align: right;">'.number_format($t_corr_rep,2).'</th>';
                                  $html.='</tr>'; 
                    $html.='</tbody>
                    </table>
                </div>';
        }
	    
	   
	    $response['html'] = $html;	
	    if($_POST['check']!='2')
	    {
    	    $response['dataPoints'] = $dataPoints;
    	    $response['dataPoints_corr'] = $dataPoints_corr;
    	    $response['dataPoints_pre'] = $dataPoints_pre;
    	    $response['current_month'] = DateTime::createFromFormat('Y-m-d', $_POST['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $_POST['f_date'])->format("Y");
    	    $response['prev_month'] = DateTime::createFromFormat('Y-m-d', $prev_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $prev_month)->format("Y");
    	    $response['corr_month'] = DateTime::createFromFormat('Y-m-d', $corre_month)->format('F').' - '.DateTime::createFromFormat("Y-m-d", $corre_month)->format("Y");
	    }	
		echo json_encode($response);
}
if($_GET['fun']=='getEmpList')
 {
     $ib = $_POST['ib'];
     $getEmplist = $obj_salesreport->getEmpList($ib);
     $html = '';
     $html.= '<option value="">Select User</option>';
     foreach($getEmplist as $list){
          $html .='<option value="'.$list['employee_id'].'">'.$list['user_name'].'</option>';
     }
     $html .='<option value="'.$ib.'">'.$_POST['name'].'</option>';
     echo $html;
 }
if($fun == 'getreport1') 
{
    parse_str($_POST['formData'], $post);
    $data=$obj_salesreport->getreport($post);
    printr($_POST['num']);
    $html = '';
    if(!empty($data))
	{
	    $html .= '<div class="table-responsive">
                    <table class="table tool-row table-striped  b-t text-small" border="1" style="width:50%;">
                        <tbody>';
                        if($post['Diff']=='0')
                        {
                                   if($_POST['num']==1)
                                        $html .= ' <tr><th colspan="7"><u>New vs Returning Customers Report</u><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports1()"><i class="fa fa-print"></i> Excel</a></span></th></tr>';
                		          
                		           $html .= '<tr>
    					                            <th colspan="7" style="background-color: beige;"><center>'.DateTime::createFromFormat('Y-m-d', $post['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $post['f_date'])->format("Y").'</center></th>
					                         </tr>
					                         <tr>';
				                            $html .= '<th rowspan="2"><center>Employee Name</center></th>
				                                      <th colspan="2"><center>New Customers</center></th>
    					                              <th colspan="2"><center>Repeated Customers</center></th>
    					                              <th rowspan="2" style="width: 30%;"><center>New VS Repeated (By Customers)</center></th>';
						          $html .= '</tr>
					                       <tr>';
					                            for($i=1;$i<=2;$i++)
					                            {
    					                             $html .= '<th style="background-color: lightblue;">Total Amount</th>
                					                          <th style="background-color: lightblue;">No. Of Customers</th>';
					                            }
					                            
					                $html .= '</tr>';
					                $curr_amt = $curr_cust = $rep_amt = $rep_cust = 0;
    		                         foreach($data as $d)
						            {     $current_email =array_intersect(explode(',',$d['previous']),explode(',',$d['curr_email']));
						                  $repeated = "'" . implode( "','", $current_email ) . "'";//printr($current_email);
						                  $repeated_amt = $obj_salesreport->getTotalRepeatamount($repeated,$post);
						                  $user_info = $obj_salesreport->getUser($d['user_id'],$d['user_type_id']);
						                  $html .= '<tr>
						                                <td>'.$user_info['name'].'</td>
						                                <td style="text-align: right;">'.($d['current_amt']-$repeated_amt['current_amt']).'</td>
						                                <td style="text-align: right;">'.($d['current_cust']-count($current_email)).'</td>
						                                <td style="text-align: right;">'.$repeated_amt['current_amt'].'</td>
						                                <td style="text-align: right;">'.count($current_email).'</td>
						                                <td><b style="color:red">New : </b>'.number_format(((($d['current_cust']-count($current_email))*100)/$d['current_cust']),2).' %<br>
                                    					    <b style="color:green">Repeated : </b>'.number_format(((count($current_email)*100)/$d['current_cust']),2).' %</td>
					                                </tr>';
					                      $curr_amt +=$d['current_amt']-$repeated_amt['current_amt'];
					                      $curr_cust +=$d['current_cust']-count($current_email);
					                      $rep_amt +=$repeated_amt['current_amt'];
					                      $rep_cust +=count($current_email);
						            }
						            
    					            $html .= '<tr><td colspan="7" style="background-color: lightblue;"></td></tr>
    					                      <tr><td colspan="7" style="background-color: beige;"><center><b>Whole Company Report</b></center></td></tr>
    					                      <tr>
    					                            <td><b>Total</b></td>
    					                            <td style="text-align: right;">'.$curr_amt.'</td>
    					                            <td style="text-align: right;">'.$curr_cust.'</td>
    					                            <td style="text-align: right;">'.$rep_amt.'</td>
    					                            <td style="text-align: right;">'.$rep_cust.'</td>
    					                            <td><b style="color:red">New : </b>'.number_format((($curr_cust*100)/($curr_cust+$rep_cust)),2).' %<br>
                                    					<b style="color:green">Repeated : </b>'.number_format((($rep_cust*100)/($curr_cust+$rep_cust)),2).' %</td>
    					                      </tr>';      
                        }
                        else if($post['Diff']=='2')
                        {
                            if($_POST['num']==1)
                              $html .= ' <tr><th colspan="7"><u>Top Most Customers</u><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports1()"><i class="fa fa-print"></i> Excel</a></span></th></tr>';
                		    
                    		    $html .= '<tr style="background-color: beige;">';
    	                            $html .= '<th>Sr. No.</th>
    	                                      <th><center>Customer Name</center></th>
    	                                      <th><center>Customer Email</center></th>
    			                              <th><center>Total Order In Amount</center></th>
    			                              <th><center>Total Order In Qty</center></th>
    			                              <th><center>Contact Owner</center></th>';
    				            $html .= '</tr>';
    				            $i=1;
    				            foreach($data as $d)
						        {   $user_info = $obj_salesreport->getUser($d['user_id'],$d['user_type_id']);//
						            $qty = $obj_salesreport->getTotalQty($d['email'],$post);
						            $html .= '<tr>
						                          <td>'.$i.'</td>
        	                                      <td>'.$d['customer_name'].'</td>
        	                                      <td>'.$d['email'].'</td>
        			                              <td style="text-align: right;">'.$d['current_amt'].'</td>
        			                              <td style="text-align: right;">'.$qty['qty'].'</td>
        			                              <th>'.$user_info['name'].'</th>
    				                          </tr>';
    				                $i++;
						        }
                        }
                        else if($post['Diff']=='3' || $post['Diff']=='4')
                        {// printr($data);
                            if($_POST['num']==1)
                              $html .= ' <tr><th colspan="7"><u>Highest No. of Customers (Sales Person Wise)</u><span class="text-muted m-l-small pull-right"><a class="label bg-success" href="javascript:void(0);" id="excel_link" onclick="getreports1()"><i class="fa fa-print"></i> Excel</a></span></th></tr>';
                		    
                    		    $html .= '<tr style="background-color: beige;">';
    	                            $html .= '<th>Sr. No.</th>
    	                                      <th><center>Highest No. Of Customer</center></th>
    			                              <th><center>Contact Owner</center></th>';
    				            $html .= '</tr>';
    				            $i=1;$cust=0;
    				            foreach($data as $d)
						        {   if($post['Diff']=='3')
						                $user_info = $obj_salesreport->getUser($d['user_id'],$d['user_type_id']);
						            else
						                $user_info = $obj_salesreport->getIndiaState($d['state_india']);
						            $html .= '<tr>
						                          <td>'.$i.'</td>
        	                                      <td style="text-align: right;">'.$d['email'].'</td>';
        			                            if($post['Diff']=='3')
        			                            {
            			                              $html .= '<th>'.$user_info['name'].'</th>';
            			                              $dataPoints [] = array("label"=>$user_info['name'], "y"=>$d['email']);
        			                            }
        			                            else
        			                            {
            			                              $html .= '<th>'.$user_info['state'].'</th>';
            			                              $dataPoints [] = array("label"=>$user_info['state'], "y"=>$d['email']);
        			                            }
    				                $html .= '</tr>';
    				                $i++;$cust+=$d['email'];
    				                
						        }
						        $html.='<tr style="background-color: lightblue;">
						                    <th>Total Customers</th>
						                    <th style="text-align: right;">'.$cust.'</th>
						                    <th></th>
						                </tr>';
						       
                        	    if($_POST['check']!='2')
                        	    {
                            	    $response['dataPoints'] = $dataPoints;
                            	    $response['current_month'] = DateTime::createFromFormat('Y-m-d', $post['f_date'])->format('F').' - '.DateTime::createFromFormat("Y-m-d", $post['f_date'])->format("Y");
                         	    }	        
                        }
        $html.='        </tbody>
                    </table>
                </div>';
	}
	$response['html'] = $html;
	// printr($response);
    echo json_encode($response);
}
?>